### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by liuqi8827** [KerryWu16/BND-DDQN#1]
Thanks for your great work!

I'm facing a problem when I run **roslaunch pioneer_utils p3_world.launch**
1. My python is 3.5
2. Tensorflow is 1.13.1
3. ROS Kinetic
4. When I run **roslaunch pioneer_utils p3_world.launch** in the terminal
The error showed in terminal is:
Traceback (most recent call last):
  **File "/opt/ros/kinetic/share/xacro/xacro.py", line 55, in <module>
    import xacro
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/xacro/__init__.py", line 35, in <module>
    import glob
  File "/usr/lib/python3.5/glob.py", line 4, in <module>
    import re
ImportError: No module named 're'**
5. I think the version of python cause this problem. However, after I change to python2.7 + ensorflow is 1.13.1 + ROS Kinetic. 
5.1 The problem is:
When I run **roslaunch pioneer_utils p3_world.launch** in the first terminal,
some ROS INFO showed in the terminal:
**SpawnModel script started
[ INFO] [1579333142.286742338]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1579333142.287142658]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1579333142.317293071]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1579333142.317689942]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1579333142.326618, 0.000000]: Loading model XML from ros parameter
[INFO] [1579333142.328966, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1579333145.353341, 0.000000]: Calling service /gazebo/spawn_urdf_model**

5.2 When I run python main.py, nothing happened. Nothing run in the Gazebo.

Can you give me some suggestions to solve this problem?
Thanks a lot!

**Comment by KerryWu16** [comment]
Hi Liu Qi,

Thank you for your interest in this work.

Your issue seems to be mainly due to the version problem. You can try the following:
1. download geometry, geometry, vision_opencv and rebuild them from source using python 3.5. You can refer to https://medium.com/@beta_b0t/how-to-setup-ros-with-python-3-44a69ca36674.
2. rename cv2.so in /opt/ros/kinetic/lib/python2.7/dist-packages to cv2_bkp.so.
3. source the workspace mentioned in 1 before running the python script.
4. The gazebo part should have no problem. You can see a square world after launching where the robot is at the center of the world.

**Comment by liuqi8827** [comment]
@KerryWu16 
Thank you for your kind reply.

I had done what you suggested(the three steps). However, I have the same problem.

1.When I run **roslaunch pioneer_utils p3_world.launch** in the terminal
The error showed in terminal is:
**Traceback (most recent call last):
File "/opt/ros/kinetic/share/xacro/xacro.py", line 55, in
import xacro
File "/opt/ros/kinetic/lib/python2.7/dist-packages/xacro/init.py", line 35, in
import glob
File "/usr/lib/python3.5/glob.py", line 4, in
import re
ImportError: No module named 're'**
2. I created a virtual environment to install tensorflow:
   2.1 mkvirtualenv -p /usr/bin/python3 BND_DDQN
   2.2 pip install tensorflow-gpu==1.13.0
   2.3 install other related dependences
3. My ROS is Kinetic
4. In the virtual environment (python3.5), on the terminal I typed the following command:
```
python
>>>import re
```
**It run successfully.**
However, When I run **roslaunch pioneer_utils p3_world.launch** in the terminal
The error occured:
**import re
ImportError: No module named 're'**

Thanks a lot!

**Comment by KerryWu16** [comment]
I guess you run the launch file in the virtualenv. You may try to open a new terminal and run the launch file outside the virtualenv.

**Comment by liuqi8827** [comment]
Hi,
Thanks for your reply. I was not available for the last couple of weeks, I am sorry for the delay

I had solved the problem of **ImportError: No module named 're'** by
change the **base.launch.xml** line 8
from
`<param name="robot_description" command="$(find xacro)/xacro.py $(find pioneer_utils)/description/urdf/pioneer3at.urdf.xacro" />`
to
`<param name="robot_description" command="$(find xacro)/xacro --inorder '$(find pioneer_utils)/description/urdf/pioneer3at.urdf.xacro' " />`
2.1However, When I run roslaunch pioneer_utils p3_world.launch in the first terminal,
some ROS INFO showed in the terminal:
SpawnModel script started
[INFO] [1581252559.769349, 0.000000]: Loading model XML from ros parameter
[INFO] [1581252559.771775, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1581252559.812704994]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1581252559.813062266]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1581252559.843234416]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1581252559.844139762]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...terminal
[INFO] [1581252562.185600, 0.000000]: Calling service /gazebo/spawn_urdf_model

**The problem is the first terminal stays there forever**

2.2 When I run python main.py in the second terminal, nothing happened. Nothing run in the Gazebo.
2.3 There is **no any error** when I run the two command in the first and second terminal.
2.4 I think something should be printed after the first terminal show the information:
**[INFO] [1581252562.185600, 0.000000]: Calling service /gazebo/spawn_urdf_model.**
However, nothing happened.

3.I want to konw your **version of ROS gazebo**.
I had test gazebo7, 8, 9. **However, it didn't work.**

**Comment by KerryWu16** [comment]
I was running Gazebo7. May I know if the gazebo GUI is running successfully? Have you run gazebo in the normal environment while run python main.py in the virtualenv? Have your checked if the topics published by Gazebo are correct?

**Comment by liuqi8827** [comment]
Thanks for your quick reply.
It run successfully.

Thanks a lot!

**Comment by liuqi8827** [comment]
I mean, I run your whole project successfully.

Thanks for your help again.

**Comment by KerryWu16** [comment]
welcome
